# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 13:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0017_auto_20170602_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Task Name')),
                ('Description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('PlannedStart', models.DateField(default=datetime.date.today, verbose_name='Planned Start')),
                ('Baseline', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Baseline')),
                ('PlannedEnd', models.DateField(verbose_name='Planned End')),
                ('Status', models.CharField(choices=[('To Plan', 'To Plan'), ('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='To Plan', max_length=30)),
                ('Complexity', models.CharField(choices=[('1', 'Very Low'), ('2', 'Low'), ('3', 'Medium'), ('4', 'High'), ('5', 'Very High')], default='2', max_length=30)),
                ('Priority', models.CharField(choices=[('1', 'Very Low'), ('2', 'Low'), ('3', 'Medium'), ('4', 'High'), ('5', 'Very High')], default='2', max_length=30)),
                ('ActualStart', models.DateTimeField(blank=True, null=True)),
                ('ActualEnd', models.DateTimeField(blank=True, null=True)),
                ('AssignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('Description', models.CharField(max_length=2000, verbose_name='Description')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project', verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Domain Name')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project', verbose_name='Project Name')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheduling.TaskCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='task',
            name='Dependance',
            field=models.ManyToManyField(related_name='_task_Dependance_+', to='Scheduling.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='Domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheduling.TaskDomain', verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='task',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project', verbose_name='Project Name'),
        ),
    ]
