# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Dependance',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_Dependance_+', to='Scheduling.Task'),
        ),
    ]
