# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0003_auto_20170608_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='Description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
