# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('Scheduling', '0004_auto_20170608_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('File', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_file', to='filer.File', verbose_name='File')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Scheduling.Task', verbose_name='Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_image', to='filer.Image', verbose_name='Image')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Scheduling.Task', verbose_name='Task')),
            ],
        ),
    ]
