# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0017_auto_20170602_1623'),
        ('Scheduling', '0006_auto_20170608_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=300, verbose_name='Functional Processus')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project', verbose_name='Project Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='PlannedEnd',
            field=models.DateField(blank=True, null=True, verbose_name='Planned End'),
        ),
        migrations.AddField(
            model_name='task',
            name='FuncProcess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scheduling.FuncProcess', verbose_name='FuncProcess'),
        ),
    ]
