# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 12:56
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0007_auto_20170621_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcprocess',
            name='Description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='taskdomain',
            name='Description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='Description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
