# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0008_auto_20170621_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Scheduling.TaskCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Scheduling.TaskDomain', verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='task',
            name='FuncProcess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Scheduling.FuncProcess', verbose_name='FuncProcess'),
        ),
    ]
