# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0009_auto_20170628_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='PlannedEnd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned End'),
        ),
        migrations.AlterField(
            model_name='task',
            name='PlannedStart',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Planned Start'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Priority',
            field=models.CharField(choices=[('5', 'Very Low'), ('4', 'Low'), ('3', 'Medium'), ('2', 'High'), ('1', 'Very High')], default='2', max_length=30),
        ),
    ]
