# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0010_auto_20170629_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='PlannedStart',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Planned Start'),
        ),
    ]
