# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=2000)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Completed', models.DateTimeField(blank=True, null=True)),
                ('Done', models.BooleanField(default=False)),
                ('Priority', models.CharField(default='2', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Todo_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group Name')),
                ('Collapse', models.BooleanField(default=False, verbose_name='Collapse ?')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Todo_Group'),
        ),
    ]
