# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Priority',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='2', max_length=2),
        ),
    ]
