# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_auto_20170602_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_group',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Group',
        ),
        migrations.AddField(
            model_name='todo',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Normal'), ('3', 'High')], default='2', max_length=2),
        ),
        migrations.DeleteModel(
            name='Todo_Group',
        ),
    ]
