# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvionmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Key', models.CharField(max_length=200, verbose_name='Key')),
                ('Value', models.CharField(max_length=200, verbose_name='Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=200, verbose_name='Environment Name')),
                ('IP', models.GenericIPAddressField(verbose_name='IP Address')),
                ('DNS', models.CharField(max_length=300, verbose_name='DNS')),
                ('MachineName', models.CharField(max_length=200, verbose_name='Machine Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='envionmentdata',
            name='Environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnvMgmt.Environment', verbose_name='Environment Name'),
        ),
    ]
