# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=200, verbose_name='Application Name')),
                ('UseIpMachineDNS', models.CharField(choices=[('IP', 'IP'), ('DNS', 'DNS'), ('MachineName', 'MachineName')], default='MachineName', max_length=30)),
                ('URLCompletion', models.CharField(max_length=300, verbose_name='URL Completion')),
                ('Environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnvMgmt.Environment', verbose_name='Environment Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SIEBEL_USERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('User', models.CharField(max_length=200, verbose_name='Username')),
                ('Password', models.CharField(max_length=200, verbose_name='Password')),
                ('EnvironmentApp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnvMgmt.EnvironmentApps', verbose_name='Application Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='EnvionmentData',
            new_name='EnvironmentData',
        ),
    ]
