# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMgmt', '0002_auto_20170708_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='siebel_users',
            name='Environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EnvMgmt.Environment', verbose_name='Environment Name'),
        ),
    ]
