# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('Slug', models.SlugField(unique=True)),
                ('Client', models.CharField(max_length=200, verbose_name='Client')),
                ('Description', tinymce.models.HTMLField(blank=True, null=True)),
                ('Start', models.DateTimeField(default=django.utils.timezone.now)),
                ('End', models.DateTimeField(blank=True, null=True)),
                ('Active', models.BooleanField(default=True)),
                ('Primary', models.BooleanField(default=False)),
                ('Administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Photo', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='filer.Image')),
                ('Tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
