# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='End',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
