# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0003_auto_20170601_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Users',
            field=models.ManyToManyField(related_name='Project_Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='Active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Client',
            field=models.CharField(max_length=200, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='End',
            field=models.DateField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Name',
            field=models.CharField(max_length=200, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='filer.Image', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Primary',
            field=models.BooleanField(default=False, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Start',
            field=models.DateField(default=datetime.date.today, verbose_name='Start'),
        ),
    ]
