# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20170601_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Users',
            field=models.ManyToManyField(related_name='Project_Users', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
