# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_auto_20170602_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='EmployeeSchedule',
        ),
        migrations.AddField(
            model_name='user_x',
            name='ScheduleUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.EmployeeSchedule', verbose_name='Schedule'),
        ),
    ]
