# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_auto_20170602_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_x',
            name='ScheduleUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.EmployeeSchedule', verbose_name='Schedule'),
        ),
    ]
