# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_auto_20170602_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalDayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayoffdate', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='NationalDayOffGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='nationaldayoff',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.NationalDayOffGroup'),
        ),
        migrations.AddField(
            model_name='user_x',
            name='NationalDayOffGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.NationalDayOffGroup', verbose_name='National Day Off Group'),
        ),
    ]
