# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_auto_20170602_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_x',
            old_name='NationalDayOffGroup',
            new_name='DayOffGroup',
        ),
    ]
