# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_auto_20170602_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='thirsday',
            new_name='thursday',
        ),
    ]
